### ISSUE TITLE
Signature validation failure

### ISSUE THREAD

**Issue by csunali** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#130]
Hi there,

Do you have any idea what could be the cause of the following error?

P.S. It used to work before and I don't think I have changed anything that could cause the issue.

```
System.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.X509SecurityKey - (thumbprint) : EF79967E8687F5959F831119124D2D903D616C5D
'.
Exceptions caught:
 'System.NullReferenceException: Object reference not set to an instance of an object.
   at System.IdentityModel.Tokens.RSACryptoServiceProviderProxy..ctor(RSACryptoServiceProvider rsa)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.X509SecurityKey.GetSignatureProvider(String algorithm, Boolean verifyOnly)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
'.
token: '{"typ":"JWT","alg":"RS256","kid":"EF79967E8687F5959F831119124D2D903D616C5D"}.{"nameid":"fc1c590d-939e-4ec7-bc01-a9f3d44e282c","sub":"fc1c590d-939e-4ec7-bc01-a9f3d44e282c","iss":"http://localhost:40000/","aud":"localhost","exp":1442354105,"nbf":1442350505}'
   at Microsoft.IdentityModel.Logging.LogHelper.Throw(String message, Type exceptionType, EventLevel logLevel, Exception innerException)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNet.Authentication.AuthenticationHandler`1.d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Builder.Extensions.MapWhenMiddleware.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass29_0.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.d__9.MoveNext()
```

**Comment by PinpointTownes** [comment]
Looks like the NRE is thrown because of this code path: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens/AsymmetricSignatureProvider.cs#L98-L112

Does it reproduce on both CLR and CoreCLR?

**Comment by csunali** [comment]
I don't have a CLR environment set for testing it, to be honest :)

So, do you mean that it is not related to OIC server that you developed? I might try downgrading the System.IdentityModel.Tokens package if you suggest so.

I would be glad if you let me know.

Cheers!

**Comment by PinpointTownes** [comment]
To confirm it's not an OIDC server bug, can you please share your JWKS? (by default, it's at `/.well-known/jwks`)

**Comment by csunali** [comment]
There you go:

```
{"keys":[{"kty":"RSA","alg":"RS256","use":"sig","x5t":"73mWfoaH9ZWfgxEZEk0tkD1hbF0","x5c":["MIICtDCCAZwCCQDO581OLFwUhjANBgkqhkiG9w0BAQQFADAcMQ0wCwYDVQQKEwRUZXN0MQswCQYDVQQGEwJUUjAeFw0xNTA2MjcyMTMzMzBaFw0xNjA2MjYyMTMzMzBaMBwxDTALBgNVBAoTBFRlc3QxCzAJBgNVBAYTAlRSMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA057jcDBtpAuQbfpRLPjXVVJI1+dh/9f+tGuTSagNW9vQaqIZDpquisoHNQK/5m5tUZFmkRXlL7ucG2Tb9ArxD1zdYP1/TJASfcOVM3dm0T89sbEf/njh1/913DxU7uJF8Of5r9hjp9G7ADOSlAhJPcUUBl7FbsfBXPPqvaE1Pqg6YXxSrhdNTb35RtRTDr1eHzIHj24Ohrk2jA62uph4SbU2sm9D0Nlc1q2q4IOg7uhMhHG851zxuzJo4snG3GVXX7visykwnXTUg7O41m46He3+krAGA3wQ34LIgsxzQ4jTGYTyYT7xw9dTTjEh5O6msxQ8R1IchD0xjsUkpmjESQIDAQABMA0GCSqGSIb3DQEBBAUAA4IBAQABVfBr8aLX3jsMoONPa50cDaPV7Acde1/Bw7TpB7ubwYMXFiO7tKwkeSUwoHj6TST3zhNHrqwXICZcf4W3puL7cBuzZO58AWQaWTUMa5dPIlc5PRfzDK5F40z7r+GWO94hjqe1K15j4sAZNgMsc0Ljiwp5PPdfLDmZHcrItTOVutqhZBYdtcxmFQFX/sw9aad5lWf69xxNUxZwctVkVNHzuDYQQJYbHLkSvFfXxz8B01JX4/BkHu97eDPYZcLjICdxScKZvD/pHD/Rdej7Hb3p0aGp/wP5o3xCdnyJR6RO/CR4sHSa9lI/v2xClkwvK/uetOcecIr9Lel9aPBTVSSv"]}]}
```

BTW, my package versions: 

```
"AspNet.Security.OpenIdConnect.Server": "1.0.0-beta3-0340",
"System.IdentityModel.Tokens": "5.0.0-beta8-209150021"
```

My OIDC server initalization:

```
            var certificate = LoadCertificate();
            var key = new X509SecurityKey(certificate);

            var credentials = new SigningCredentials(key,
                SecurityAlgorithms.RsaSha256Signature,
                SecurityAlgorithms.Sha256Digest);

            string issuer = configuration["Security:OpenId:Issuer"];

            app.UseOpenIdConnectServer(options =>
            {
                options.AuthenticationScheme = OpenIdConnectDefaults.AuthenticationScheme;

                options.Issuer = !string.IsNullOrEmpty(issuer) ? new Uri(issuer) : null;

                options.SigningCredentials.Add(credentials);

                options.Provider = new OpenIdAuthorizationProvider();

                options.ApplicationCanDisplayErrors = true;
                options.AllowInsecureHttp = true;

                options.TokenEndpointPath = new PathString("/Auth/Token");
                options.LogoutEndpointPath = new PathString("/Auth/Logout");
            });
```

My JWT initialization:

```
            app.UseJwtBearerAuthentication(options =>
            {
                options.AutomaticAuthentication = true;
                options.Authority = configuration["Security:OAuth:Authority"];
                options.Audience = configuration["Security:OAuth:Audience"];

                // if the audience is null or empty, then don't validate it
                options.TokenValidationParameters.ValidateAudience = configuration["Security:OAuth:Audience"] != null;
            });
```

Hope the additional info can be of some help.

BR.

**Comment by PinpointTownes** [comment]
If you have time to test it under dnx451, give it a try. This bug - which is definitely not caused by the server - may be caused by some recent changes in CoreFX.

**Comment by PinpointTownes** [comment]
It's an IdentityModel bug, caused by the fact `certificate.GetRSAPublicKey` can now return a `RSACng` instance - instead of a `RSACryptoServiceProvider` - on platforms supporting CNG. Since IdentityModel expects a `RSACryptoServiceProvider`, the cast fails and the `rsa` variable is null on CoreCLR.

```csharp
var certificate = LoadCertificate();

#if DNXCORE50
var key = certificate.GetRSAPublicKey(); // may be a RSACng instance.
#else
var key = certificate.PublicKey.Key; // will be a RSACryptoServiceProvider.
#endif
```

I created a ticket on the AzureAD repository owning IdentityModel: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/247

In the meantime, try switching to dnx451 (since it's not impacted) or directly use a RSA key, since the code path is not the same.

**Comment by csunali** [comment]
I'm spending some time trying to make my project support dnx451. It seems that the `Dictionary<TKey, TValue>.ValueCollection` does not implement the `IReadOnlyCollection<TValue>` interface. Found it quite interesting. Is that really the case or am I missing something with dnx451?

Just asking for your experiences, thinking that you already have quite an experience with dnx451.

Thank you for the above details, I will try it as soon as I have the dnx451 ready :)

BR.

**Comment by PinpointTownes** [comment]
No answer from the Azure AD team yet.

If you wanna try to prioritize this item, you can ping @vibronet on Twitter (though he's currently at #TECHintersection).

**Comment by csunali** [comment]
That is fine. 451 seems to handle the issue and I can work using 451 up until the issue is fixed.

Please close the issue if you think you don't need to keep it up here :)

Best regards!

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/37b116d83a57e81397d25ecce8109066c378dc41.
