### ISSUE TITLE
No RSA implementation compatible exception on ubuntu using CoreCLR

### ISSUE THREAD

**Issue by ryanschuler** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#202]
Using RC2 nightlies. Project uses Sqlite, EF7, CoreCLR and kestrel with nginx. The Linux box uses Ubuntu 14.04.3 which is on a fairly slow machine (Digital Ocean $5 droplet)

I am currently attempting to run the project with the CoreCLR instead of Mono but ran into an issue.

This error does not throw using Mono.

```
System.PlatformNotSupportedException: No RSA implementation compatible with your configuration can be found.
```

Log:
```
warn: AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware[0]
      No explicit signing credentials have been registered. Using a X.509 certificate stored in the machine store is recommended for production environments.
System.PlatformNotSupportedException: No RSA implementation compatible with your configuration can be found.
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHelpers.GenerateKey(IRuntimeEnvironment environment)
   at Microsoft.AspNet.Builder.OpenIdConnectServerExtensions.UseOpenIdConnectServer(IApplicationBuilder app, OpenIdConnectServerOptions options)
   at Microsoft.AspNet.Builder.OpenIddictExtensions.<>c__DisplayClass3_0.<UseOpenIddictCore>b__2(IApplicationBuilder map)
   at Microsoft.AspNet.Builder.OpenIddictExtensions.UseOpenIddictCore(IApplicationBuilder app, Action`1 configuration)
   at Fortelinea.Updates.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, IDatabaseInitializer databaseInitializer, ILoggerFactory loggerFactory, IRuntimeEnvironment runtimeEnvironment)
```

Source of exception:
```
internal static RSA GenerateKey(IRuntimeEnvironment environment) {
    if (string.Equals(environment.OperatingSystem, "Windows", StringComparison.OrdinalIgnoreCase)) {
#if DNXCORE50
        // On CoreCLR, use RSACng.
        return new RSACng(2048);
#else
        // On desktop CLR, use RSACryptoServiceProvider.
        return new RSACryptoServiceProvider(2048);
#endif
    }

    // When the runtime is identified as Mono, use RSACryptoServiceProvider independently of the operating system.
    if (string.Equals(environment.RuntimeType, "Mono", StringComparison.OrdinalIgnoreCase)) {
        return new RSACryptoServiceProvider(2048);
    }

#if DNXCORE50
    // On Linux and Darwin, use RSAOpenSsl when running on CoreCLR.
    if (string.Equals(environment.OperatingSystem, "Linux", StringComparison.OrdinalIgnoreCase) ||
        string.Equals(environment.OperatingSystem, "Darwin", StringComparison.OrdinalIgnoreCase)) {
        return new RSAOpenSsl(2048);
    }
#endif

    // If no appropriate implementation can be found, throw an exception.
    throw new PlatformNotSupportedException("No RSA implementation compatible with your configuration can be found.");
}
```

It throws the PlatformNotSupportedException when attempting to use dnx run.  I had it log my environment.OperatingSystem and it turns out it is 'ubuntu' rather than 'linux'.

**Comment by PinpointTownes** [comment]
Thanks for reporting this bug! :smile: 

It looks like a major breaking change has been added to the platform abstractions we're using to determine the operating system at runtime: https://github.com/aspnet/PlatformAbstractions/pull/9. 

Luckily, a new `OperatingSystemPlatform` property has been added to `IRuntimeEnvironment`, so we should be able to use it to replace the now inappropriate `OperatingSystem`.

I'll create a fix and send a PR :smile:

**Comment by PinpointTownes** [comment]
In the meantime, you can use a X509 certificate (which is the recommended approach for production) to work around this bug:

```csharp
app.UseOpenIdConnectServer(options => {
    var certificate = new X509Certificate2("path to your certificate", "certificate password");
    options.SigningCredentials.AddCertificate(certificate);
});
```

**Comment by PinpointTownes** [comment]
AppVeyor is pushing a new package to MyGet. Give it a few minutes and run `dnu restore --no-cache` to download the latest package.

Don't hesitate to ping me if you're still seeing this bug.

**Comment by gregbty** [comment]
Any tips for handling this within an Azure website/app?

**Comment by PinpointTownes** [comment]
@gregbty when going live, using a X509 certificate is the recommended approach.
