### ISSUE TITLE
"Failed to validate the Token" there is a key at /well-known/jwks

### ISSUE THREAD

**Issue by wesamco** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#232]
repro https://github.com/wesamco/prepro, just change in project.json
`"Microsoft.Extensions.DependencyModel": "1.0.0-*",`
 to
`        "Microsoft.Extensions.DependencyModel": "1.0.0-beta-002202",
`
# Exception 
```
 info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 OPTIONS http://localhost:5000/api/ticket
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 7.8808ms 204
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/api/ticket
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[1]
      Failed to validate the token eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZFRlNGU0RKVVo1MDlDNzdZQ0U2WTFaVF9fUUxMOFo4X0YyQVpLM0MifQ.eyJ1bmlxdWVfbmFtZSI6ItmI2LPYp9mFLtiz2LnYryIsImVtYWlsIjoi2YjYs9in2YUu2LPYudivIiwicm9sZSI6IkFkbWluIiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiI3ZjI4NTBlZi0yNzViLTRmNjQtODc2NC1jNThiN2RmM2U5NzgiLCJnaXZlbl9uYW1lIjoi2YjYs9in2YUu2LPYudivIiwidXNhZ2UiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZSI6WyJvZmZsaW5lX2FjY2VzcyIsInByb2ZpbGUiLCJlbWFpbCIsInJvbGVzIl0sInN1YiI6ImE3NTY5ODkwLTAzNzMtNGQ1YS05Zjk0LTc1NTRhMDkzNzM5NCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC8iLCJuYmYiOjE0NTk3MTY3NTIsImV4cCI6MTQ2MjM5NTE1MiwiaWF0IjoxNDU5NzE2NzUyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAvIn0..
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10504: Unable to validate signature, token does not have a signature: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZFRlNGU0RKVVo1MDlDNzdZQ0U2WTFaVF9fUUxMOFo4X0YyQVpLM0MifQ.eyJ1bmlxdWVfbmFtZSI6ItmI2LPYp9mFLtiz2LnYryIsImVtYWlsIjoi2YjYs9in2YUu2LPYudivIiwicm9sZSI6IkFkbWluIiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiI3ZjI4NTBlZi0yNzViLTRmNjQtODc2NC1jNThiN2RmM2U5NzgiLCJnaXZlbl9uYW1lIjoi2YjYs9in2YUu2LPYudivIiwidXNhZ2UiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZSI6WyJvZmZsaW5lX2FjY2VzcyIsInByb2ZpbGUiLCJlbWFpbCIsInJvbGVzIl0sInN1YiI6ImE3NTY5ODkwLTAzNzMtNGQ1YS05Zjk0LTc1NTRhMDkzNzM5NCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC8iLCJuYmYiOjE0NTk3MTY3NTIsImV4cCI6MTQ2MjM5NTE1MiwiaWF0IjoxNDU5NzE2NzUyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAvIn0.'
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[7]
      Bearer was not authenticated. Failure message: IDX10504: Unable to validate signature, token does not have a signature: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZFRlNGU0RKVVo1MDlDNzdZQ0U2WTFaVF9fUUxMOFo4X0YyQVpLM0MifQ.eyJ1bmlxdWVfbmFtZSI6ItmI2LPYp9mFLtiz2LnYryIsImVtYWlsIjoi2YjYs9in2YUu2LPYudivIiwicm9sZSI6IkFkbWluIiwiQXNwTmV0LklkZW50aXR5LlNlY3VyaXR5U3RhbXAiOiI3ZjI4NTBlZi0yNzViLTRmNjQtODc2NC1jNThiN2RmM2U5NzgiLCJnaXZlbl9uYW1lIjoi2YjYs9in2YUu2LPYudivIiwidXNhZ2UiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZSI6WyJvZmZsaW5lX2FjY2VzcyIsInByb2ZpbGUiLCJlbWFpbCIsInJvbGVzIl0sInN1YiI6ImE3NTY5ODkwLTAzNzMtNGQ1YS05Zjk0LTc1NTRhMDkzNzM5NCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC8iLCJuYmYiOjE0NTk3MTY3NTIsImV4cCI6MTQ2MjM5NTE1MiwiaWF0IjoxNDU5NzE2NzUyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAvIn0.'
warn: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware[12]
      AuthenticationScheme: Bearer was challenged.
info: Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler[2]
      Executed action TicketController.Get (project) in 1.2953ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 20.544ms 401
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/.well-known/jwks
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3.1701ms 200 application/json;charset=UTF-8

```
# Environment data
```
λ dotnet --info
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

```

**Comment by PinpointTownes** [comment]
Thanks for reporting this bug.

Sadly, it's not caused by ASOS but by IdentityModel, the MSFT library responsible of serializing our JWTs. I moved your ticket to the appropriate repo and pinged @brentschmaltz and @tushargupta51 who are in charge of this stack: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/360

In the meantime, you can switch to opaque tokens (the new default format in ASOS beta5/OpenIddict).

**Comment by brentschmaltz** [comment]
@wesamco fix was committed today, https://www.myget.org/feed/azureadwebstacknightly/package/nuget/System.IdentityModel.Tokens.Jwt
5.0.0-rc2-304061127

**Comment by PinpointTownes** [comment]
@brentschmaltz thanks!

@wesamco the updated package is not on the aspnetcidev feed yet. If you want to use it, I'd suggest referencing the `azureadwebstacknightly`, as indicated by @brentschmaltz.

**Comment by wesamco** [comment]
@brentschmaltz @PinpointTownes  Thnaks.
I added the AzureAdwebstacknightly feed to my nuget.config, then specfied in project.json to install the latest "System.IdentityModel.Tokens.Jwt": "5.0.0-rc2-304061127", made sure it installed 5.0.0-rc2-304061127 by checking project.lock.json, compiled and ran tried to issue new ticket and this happened:
# Exception 
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.MissingMethodException: Method not found: 'Void Microsoft.IdentityModel.Tokens.SecurityTokenDescriptor.set_Claims(System.Collections.Generic.IEnumerable`1<System.Security.Claims.Claim>)'.
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<SerializeAccessTokenAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.SerializeAccessTokenAsync(ClaimsPrincipal principal, AuthenticationProperties properties, OpenIdConnectMessage request, OpenIdConnectMessage response)
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<InvokeTokenEndpointAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<HandleRequestAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HKQV2J35BDD6" communication error
Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -4081 ECANCELED operation canceled
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 692.2686ms 500 text/html; charset=utf-8
```

**Comment by PinpointTownes** [comment]
Ah yeah, `SecurityTokenDescriptor.Claims` was replaced by `SecurityTokenDescriptor.Subject`.
I'll update that, but it will have to wait until the fixed IdentityModel is on the aspnetcidev feed.

**Comment by PinpointTownes** [comment]
The aspnetcidev feed has been updated, but for some reasons, the IdentityModel packages haven't been pushed to this feed. Looks like we'll have to wait a bit more.

**Comment by PinpointTownes** [comment]
@Eilon yo! Looks like you're finalizing the RC2 packages at this moment. It's absolutely critical to include the latest IdentityModel packages as they fix a terrible bug in the JWT security token handler, but AFAIK, they are not on the aspnetcidev/aspnetcirelease feeds. Was it already too late to include them in the RC2 release?

**Comment by Eilon** [comment]
@PinpointTownes definitely not too late. We'll work with @brentschmaltz to work on getting the new build.

**Comment by PinpointTownes** [comment]
Reopening, as we'll have to make the `SecurityTokenDescriptor.Claims` -> `SecurityTokenDescriptor.Subject` change.

@Eilon thanks! :tada:

**Comment by wesamco** [comment]
:shipit:

**Comment by PinpointTownes** [comment]
Fixed by https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/237/commits/e3a8781af075157af944d575d441bab3e7773a05. The updated package is now on MyGet.
