### ISSUE TITLE
Remove the IdentityModel bug workaround in AddEphemeralKey when targeting >5.0.1-preview1

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#348]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/477 should be fixed in 5.0.1-preview1. 

``` csharp
// Note: the RSA instance cannot be flowed as-is due to a bug in IdentityModel that disposes
// the underlying algorithm when it can be cast to RSACryptoServiceProvider. To work around
// this bug, the RSA public/private parameters are manually exported and re-imported when needed.
SecurityKey key;
if (rsa is RSACryptoServiceProvider) {
    var parameters = rsa.ExportParameters(includePrivateParameters: true);
    key = new RsaSecurityKey(parameters);
    key.KeyId = key.GetKeyIdentifier();

    // Dispose the algorithm instance.
    rsa.Dispose();
}
```

**Comment by PinpointTownes** [comment]
Postponed to the next milestone, as ASP.NET Core 1.1.0 is impacted by a bunch of annoying bugs.

**Comment by BrainCrumbz** [comment]
Just tried with AspNet.Security.OpenIdConnect.Server 1.0.0-beta7-final and .NET Core 1.1.0, and we're hitting this exception at startup, which basically gives a 500 error on client:

> Microsoft.Extensions.DependencyInjection.DataProtectionServices:Information: User profile is available. Using 'C:\Users\XXXXX\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Critical: Application startup exception

> System.ArgumentException: At least one signing key must be registered. Consider registering a X.509 certificate or call 'options.SigningCredentials.AddEphemeralKey()' to generate and register an ephemeral signing key.
Parameter name: options
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware..ctor(RequestDelegate next, IOptions`1 options, IHostingEnvironment environment, ILoggerFactory loggerFactory, HtmlEncoder htmlEncoder, UrlEncoder urlEncoder, IDataProtectionProvider dataProtectionProvider)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 DEBUG http://localhost:51254/  0
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:51254/  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 455.5732ms 500 text/html; charset=utf-8
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HL0PP8AHC1TP": An unhandled exception was thrown by the application.

> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FrameResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.ValidateState(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at Microsoft.AspNetCore.Hosting.Views.ErrorPage.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.RazorViews.BaseView.<ExecuteAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

On a side note, the upgrade required to insert some `using AspNet.Security.OpenIdConnect.Primitives;` where constants were used

**Comment by PinpointTownes** [comment]
It's not an issue. Read the exception message and my last blog post, and you'll immediately understand what's wrong.

**Comment by BrainCrumbz** [comment]
Just for future reference, here's the blog post link: http://kevinchalet.com/2016/11/30/the-new-aspnet-contrib-packages-are-out/

**Comment by BrainCrumbz** [comment]
Confirmed: not an issue. It was enough, at least for development environment, to add `options.SigningCredentials.AddEphemeralKey();` within `app.UseOpenIdConnectServer(options => ...)`

**Comment by PinpointTownes** [comment]
Fixed as part of https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/4a6224177d1a3d33a2f3e523805b3e8cf0e11c98.
