### ISSUE TITLE
Exception: An identity cannot be extracted from this request

### ISSUE THREAD

**Issue by yang-xiaodong** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#480]
Hi Kévin~

 This is a great library, I'm used this library in my project, thank you。
 When I upgrade to ASP.NET Core 2.0 , I met an exception at the API authorization stage. 

MyGet  package: **AspNet.Security.OpenIdConnect.Server**　
package version: **2.0.0-rc1-1314**

**Startup.cs**
``` cs
 //ConfigureServices
 services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(options =>
                {
                    options.Cookie.Name = "example.cookie";
                    options.Cookie.HttpOnly = true;
                    options.LoginPath = "/Exp/Login";
                })
                .AddOpenIdConnectServer(options => {
                    options.AllowInsecureHttp = true;
                    options.TokenEndpointPath = "/connect/token";
                    options.LogoutEndpointPath = "/connect/logout";
                    options.ApplicationCanDisplayErrors = true;
                    options.AccessTokenLifetime = TimeSpan.FromDays(1);
                    options.ProviderType = typeof(AuthorizationProvider);
                });
//Configure
app.UseAuthentication();
```
The `AuthorizationProvider.cs`   is basically consistent with the README.md, I can get access tokens normally.

**ApiController.cs**
```
[Authorize(AuthenticationSchemes = "ASOS")]
public class AuthBaseController : ControllerBase
{
    [HttpGet("~/api/testauth")]
    public IActionResult Test(){

   }
}
```

### Repetition
![image](https://user-images.githubusercontent.com/8205994/30949176-7896422a-a447-11e7-9bd9-07a0f12af721.png)

![image](https://user-images.githubusercontent.com/8205994/30949145-4f2c84d0-a447-11e7-8a59-eb978041ae00.png)

### Error

`context.Features.Get<OpenIdConnectServerFeature>() `  is return **null**

```
System.InvalidOperationException: An identity cannot be extracted from this request.
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<HandleAuthenticateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<AuthenticateAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<AuthenticateAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by kevinchalet** [comment]
Hey @yuleyule66,

That's the expected behavior. ASOS will refuse to validate access tokens for endpoints it doesn't manage, which means it can't be used to decrypt access tokens for your API controllers.

Instead, reference and register the OAuth2 validation handler like in the sample and use `[Authorize(AuthenticationSchemes = OAuthValidationDefaults.AuthenticationScheme)]`.

**Comment by yang-xiaodong** [comment]
I tried to use `[Authorize(AuthenticationSchemes = OAuthValidationDefaults.AuthenticationScheme)]`, but I get:
```
System.InvalidOperationException: No authentication handler is configured to authenticate for the scheme: Bearer
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<AuthenticateAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.<AuthenticateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by kevinchalet** [comment]
Have you registered the validation handler? The message says you haven't.

**Comment by yang-xiaodong** [comment]
How to register validation handler ? Any examples?

**Comment by kevinchalet** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Startup.cs#L48

**Comment by yang-xiaodong** [comment]
Yes, I haven't registered,  it works now.  Thank you very much, have a nice day.
