### ISSUE TITLE
No authenticationScheme was specified

### ISSUE THREAD

**Issue by eestein** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#512]
Hi! I'm using v2.0.0-rc2-final and I can't login to my app.
I'm able to generate the token correctly, but when I try to login with that token this error is thrown:

>System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.

This is the setup:

```csharp
services
    .AddAuthorization(auth =>
    {
        auth.AddPolicy("Bearer",
            new AuthorizationPolicyBuilder()
                .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
                .RequireAuthenticatedUser()
                .Build()
        );
    })
    .AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    })
    .AddOpenIdConnectServer(options =>
    {
        options.Provider = new AuthorizationProvider(
            services.BuildServiceProvider().GetService<ExceptionMessages>(),
            (IUnitOfWork<DefaultSecurityContext>)services.BuildServiceProvider().GetService<IUnitOfWork>()
        );

        options.AuthorizationEndpointPath = Constants.Security.Paths.AuthorizationEndpoint;
        options.LogoutEndpointPath = Constants.Security.Paths.LogoutEndpoint;
        options.TokenEndpointPath = Constants.Security.Paths.TokenEndpoint;
        options.UserinfoEndpointPath = Constants.Security.Paths.UserInfoEndpoint;

        options.ApplicationCanDisplayErrors = true;
        options.AllowInsecureHttp = true;

        if (useJwt)
        {
            options.AccessTokenHandler = new JwtSecurityTokenHandler
            {
                InboundClaimTypeMap = new Dictionary<string, string>(),
                OutboundClaimTypeMap = new Dictionary<string, string>()
            };

            options.SigningCredentials.AddCertificate(Certificate.Default);

            if (useEphemeralKey)
                options.DataProtectionProvider = new EphemeralDataProtectionProvider(new LoggerFactory());
        }
    });
```

And detailed exception:

```
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<ChallengeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1231.6994ms 500
```

Any ideas? I can't login :/

**Comment by eestein** [comment]
I found the answer on OpenIddict repository:

https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Startup.cs

I was missing: `AddOAuthValidation`, but now the following error is thrown:

> Bearer was not authenticated. Failure message: Authentication failed because the access token was invalid.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: (null).
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.

**Comment by kevinchalet** [comment]
Yo.

It's not caused by the OIDC server handler. I suspect this is caused by the fact you're not calling `AddJwtBearer()` (or `AddOAuthValidation()` when using the default token format).

Note: you should consider using `ProviderType` instead of doing manual DI resolution.

**Comment by eestein** [comment]
@PinpointTownes :) thanks, I had just figured that out... could you check my comment? Now it's not authenticating... Also, what do you mean with:

>Note: you should consider using ProviderType instead of doing manual DI resolution.

Thanks for your help and hard work :)

**Comment by kevinchalet** [comment]
> Also, what do you mean with:

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Startup.cs#L52

> Now it's not authenticating...

Are you trying to validate a JWT token with the validation handler? It only supports the default token format.

> Thanks for your help and hard work :)

Thanks!

**Comment by eestein** [comment]
@PinpointTownes 

>https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Startup.cs#L52

Cool! Just changed that.

>Are you trying to validate a JWT token with the validation handler? It only supports the default token format.


So... I've been reading a lot (and also learned a lot) from your tutorials on your site and by digging through your projects' source code. But I'm not sure what do you mean by validation handler. Is that something I should've implemented in order to use JWT? Is this related to `TokenValidationParameters`

Sorry for my ignorance... I might've missed that

**Comment by eestein** [comment]
After some debugging:

```csharp
.AddJwtBearer(options =>
                {
                    options.Events = new JwtBearerEvents
                    {
                        OnChallenge = context =>
                        {
                            var x = 2;
                            return Task.CompletedTask;
                        },
                        OnAuthenticationFailed = context =>
                        {
                            var x = 2;
                            return Task.CompletedTask;
                        },
                        OnMessageReceived = context =>
                        {
                            var x = 2;
                            return Task.CompletedTask;
                        },
                        OnTokenValidated = context =>
                        {
                            var x = 2;
                            return Task.CompletedTask;
                        }
                    };
                    //options.TokenValidationParameters
                })
```

it looks like it's related to my lack of setting up `AddJwtBearer`. I'm going to try to do that now.

**Comment by kevinchalet** [comment]
Yes, you must at least specify the `Audience` (that must match the value used when calling `ticket.SetResources("...")` and the `Authority`, which is the HTTP(S) address of your server.

If you prefer a configurationless approach, go with the default token format and the validation handler (registered when you call `AddOAuthValidation()`).

**Comment by eestein** [comment]
Thank you for your help, it's working now, I was missing a few things. Here's the complete working code:

```csharp
services
    .AddAuthorization(auth =>
    {
        auth.AddPolicy("Bearer",
            new AuthorizationPolicyBuilder()
                .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
                .RequireAuthenticatedUser()
                .Build()
        );
    })
    .AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    })
    .AddJwtBearer(options =>
    {
        options.RequireHttpsMetadata = Constants.Server.Environment == EnvironmentType.Production;
        options.Audience = Constants.Security.Token.Audience;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuerSigningKey = true,
            IssuerSigningKey = Certificate.PublicKey,
            ValidateIssuer = true,
            ValidIssuer = Constants.Security.Token.Issuer,
            ValidateAudience = true,
            ValidateLifetime = true
        };
    })
    .AddOpenIdConnectServer(options =>
    {
        options.ProviderType = typeof(AuthorizationProvider);

        options.AuthorizationEndpointPath = Constants.Security.Paths.AuthorizationEndpoint;
        options.LogoutEndpointPath = Constants.Security.Paths.LogoutEndpoint;
        options.TokenEndpointPath = Constants.Security.Paths.TokenEndpoint;
        options.UserinfoEndpointPath = Constants.Security.Paths.UserInfoEndpoint;

        options.ApplicationCanDisplayErrors = true;
        options.AllowInsecureHttp = Constants.Server.Environment != EnvironmentType.Production;

        if (useJwt)
        {
            options.AccessTokenHandler = new JwtSecurityTokenHandler
            {
                InboundClaimTypeMap = new Dictionary<string, string>(),
                OutboundClaimTypeMap = new Dictionary<string, string>()
            };

            options.SigningCredentials.AddCertificate(Certificate.Default);

            if (useEphemeralKey)
                options.DataProtectionProvider = new EphemeralDataProtectionProvider(new LoggerFactory());
        }
    });
``` 

You're a gentleman and a scholar! :)
